# Generated by Django 4.2.3 on 2024-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque nisi a adipisci sapiente culpa, ipsum quos et facilis? Obcaecati doloremque sit non facilis molestiae eaque necessitatibus dolorem exercitationem saepe corrupti?', max_length=500),
        ),
    ]
